ls: cannot access './3003/photos': No such file or directory
starting from scratch 
                                         version_number       10108
At line 1848 of file ../private/ctrls_io.f90 (unit = 30, file = '/hpc/group/physics/al363/sens/base/inlist_base_adaptive')
Fortran runtime error: Cannot match namelist object name 1

Error termination. Backtrace:
#0  0x7fdd6bd7cdec in finalize_transfer
	at /root/mesasdk-src/gcc/libgfortran/io/transfer.c:3891
#1  0x489864 in __ctrls_io_MOD_read_controls_file
	at ../private/ctrls_io.f90:1848
#2  0x489aa0 in __ctrls_io_MOD_read_controls_file
	at ../private/ctrls_io.f90:1887
#3  0x489d27 in __ctrls_io_MOD_read_controls
	at ../private/ctrls_io.f90:1804
#4  0x489d95 in __ctrls_io_MOD_do_one_setup
	at ../private/ctrls_io.f90:1774
#5  0x437705 in __run_star_support_MOD_before_evolve_loop
	at ../job/run_star_support.f90:277
#6  0x438108 in __run_star_support_MOD_run1_star
	at ../job/run_star_support.f90:94
#7  0x41c710 in __run_star_MOD_do_run_star
	at /hpc/group/physics/al363/mesa10108/star/job/run_star.f:26
#8  0x41c761 in run
	at ../src/run.f:13
#9  0x41c798 in main
	at ../src/run.f:2
 read /hpc/group/physics/al363/sens/base/inlist_base_adaptive




Failed while trying to read control namelist file: /hpc/group/physics/al363/sens/base/inlist_base_adaptive
Perhaps the following runtime error message will help you find the problem.

